#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if [ "$1" = "remove" ]; then

    if [ -e /etc/logrotate.d/stream-radio ]; then
        rm /etc/logrotate.d/stream-radio
    fi

    if [ -e /etc/init/stream-radio.conf ]; then
        rm /etc/init/stream-radio.conf
    fi

    if [ -e /var/run/stream-schedule/stream-radio.pid ]; then
        rm /var/run/stream-schedule/stream-radio.pid
    fi

    if [ -e /var/log/upstart/stream-radio.log ]; then
        rm -r /var/log/upstart/stream-radio*
    fi

    if [ -e /var/log/stream-schedule/stream-radio.log ]; then
        rm -r /var/log/stream-schedule/stream-radio*
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -e /etc/stream-schedule/radio/ ]; then
        rm -r /etc/stream-schedule/radio/
    fi
fi

if isSystemd; then
	echo "reload systemd services"
	systemctl daemon-reload
fi

exit 0;

#DEBHELPER#
